const fs = require('fs');
const path = require('path');

// Comprehensive dictionary providing high-level 4-5 line technical definitions for every single keyword
// written from the perspective of a Senior / Lead Software Engineer & Systems Architect (10+ years experience).

const dictionary = {
  // --- Top 25 Must-Have ---
  "C#": "Modern, type-safe, object-oriented language developed by Microsoft executing on the cross-platform .NET runtime. It provides high-performance memory primitives such as Span<T>, Memory<T>, and ref struct alongside rich functional language features like pattern matching and records. In enterprise systems, it serves as the foundational language for resilient microservices, high-throughput financial transaction engines, and scalable REST/gRPC backend services.",
  "ASP.NET Core": "Cross-platform, open-source web framework optimized for high-throughput, low-allocation cloud services and microservices. It features an integrated dependency injection container, modular middleware request pipeline, and Kestrel web server capable of handling millions of requests per second. Used as the core platform for exposing RESTful Web APIs, GraphQL services, and real-time bidirectional SignalR hubs.",
  "Web API": "Stateless HTTP service architecture built on ASP.NET Core that exposes domain capabilities to SPAs, mobile applications, and third-party integrations. It natively supports model validation, content negotiation, action filters, OpenAPI/Swagger specifications, and RFC 7807 problem details error handling. Standardized across enterprise platforms to decouple presentation tiers from core backend microservice ecosystems.",
  "Entity Framework Core": "Modern Object-Relational Mapper (ORM) for .NET enabling developers to query relational and NoSQL databases using strongly typed C# LINQ expressions. Provides change tracking, database schema migrations, and relationship mapping with support for optimized query modes like AsNoTracking and AsSplitQuery. Utilized in enterprise transactional systems to accelerate domain model persistence while isolating SQL dialect specifics.",
  "SQL Server": "Enterprise relational database management system (RDBMS) providing ACID transaction guarantees, advanced indexing (Clustered, Non-Clustered, Filtered, Columnstore), and execution plan optimization. In high-concurrency enterprise architectures, it manages core financial ledgers and transactional relational entities. Performance tuning involves analyzing query execution plans, resolving deadlocks, and optimizing index seek vs table scan operations.",
  "Angular": "Comprehensive, opinionated TypeScript-based single-page application (SPA) framework developed by Google featuring hierarchical dependency injection, modular architecture, and reactive state management. Employs RxJS streams for asynchronous operations and fine-grained Angular Signals for efficient DOM change detection without Zone.js overhead. Widely adopted for mission-critical enterprise portals and multi-team intranet dashboards.",
  "Microservices": "Architectural style decomposing complex applications into autonomous, loosely coupled services organized strictly around bounded business domains. Each microservice manages its own private database, CI/CD pipeline, and horizontal scaling lifecycle while communicating via synchronous gRPC/REST or asynchronous messaging. Improves fault isolation and team velocity at the expense of distributed transaction and tracing complexity.",
  "Distributed Systems": "Computing architecture where networked autonomous components communicate by message passing to achieve a unified business objective. Governed by the CAP theorem and PACELC principles, distributed systems require explicit design for network partitions, latency variance, and eventual consistency. Key patterns include distributed consensus, idempotency keys, leader election, and saga compensation workflows.",
  "REST APIs": "Architectural style for distributed networked services utilizing standard HTTP methods (GET, POST, PUT, DELETE, PATCH), stateless communication, and standard resource URIs. Leverages HTTP caching headers (ETag, Cache-Control) and status codes for uniform client-server interactions. In enterprise ecosystems, REST serves as the primary external contract for public APIs and Backend-For-Frontend (BFF) layers.",
  "Authentication & JWT": "Security mechanism where user identities are verified and represented as compact, digitally signed JSON Web Tokens (RFC 7519) containing verifiable claims. Microservices cryptographically validate JWT signatures locally using public key sets (JWKS) without making round-trip database queries to a central session store. Requires disciplined token lifecycle management, short expiry windows, and secure refresh token rotation.",
  "OAuth2 / OIDC": "Industry-standard delegated authorization framework (OAuth 2.0) paired with an identity verification layer (OpenID Connect) providing signed ID tokens. Protects APIs by exchanging authorization codes with PKCE for scoped access tokens without exposing raw user credentials. Standardized across enterprise solutions using identity providers like Microsoft Entra ID (Azure AD), Okta, and Auth0 for Single Sign-On (SSO).",
  "AWS Services": "Comprehensive cloud platform delivering elastic compute, storage, networking, and managed serverless primitives (Lambda, ECS, EKS, DynamoDB, S3, SQS, SNS, EventBridge). Used to architect multi-region, highly available cloud-native solutions with infrastructure-as-code automation. Employs fine-grained IAM roles, VPC isolation, and CloudWatch telemetry for enterprise governance.",
  "Docker": "Containerization technology that packages applications and all runtime dependencies into immutable, portable OCI-compliant container images. Eliminates 'works on my machine' environmental discrepancies across development, staging, and production Kubernetes clusters. Utilizes multi-stage Dockerfiles to minimize attack surfaces and optimize image layer caching.",
  "Kubernetes": "Production-grade container orchestration engine automating deployment, scaling, load balancing, self-healing, and networking of containerized workloads. Manages Pod scheduling across worker nodes, Ingress traffic routing, Horizontal Pod Autoscaling (HPA), and zero-downtime rolling updates. Deployed via managed cloud offerings (EKS/AKS) with GitOps workflows and Helm charts.",
  "CI/CD": "Continuous Integration and Continuous Delivery automation practices using pipelines (GitHub Actions, Jenkins, CircleCI) to compile, test, scan, and deploy code changes. Enforces quality gates via static analysis (SonarQube), container security vulnerability scans (Trivy), and automated unit/integration suites. Enables rapid, low-risk releases through blue-green, canary, and rolling deployment strategies.",
  "System Design": "Engineering discipline of architecting end-to-end scalable, resilient, and maintainable software systems balancing High-Level (HLD) and Low-Level (LLD) requirements. Evaluates trade-offs between consistency, availability, latency, and throughput across compute, data storage, and network layers. Essential for designing large-scale distributed architectures capable of handling massive concurrency and data volume.",
  "DDD": "Domain-Driven Design is a software design methodology focusing on modeling software to match complex real-world business domains. Establishes a Ubiquitous Language between engineers and domain experts, encapsulating business rules within Bounded Contexts, Aggregate Roots, Entities, and Value Objects. Keeps domain models pure and decoupled from infrastructure or persistence mechanisms.",
  "Clean Architecture": "Layered architectural pattern emphasizing the Dependency Inversion Principle, where dependencies point strictly inward toward enterprise domain rules. Isolates business use cases from UI frameworks, database drivers, and third-party APIs. Maximizes testability and system longevity by allowing infrastructure components to be swapped without altering core business rules.",
  "CQRS": "Command Query Responsibility Segregation separates data modification operations (Commands) from data retrieval operations (Queries) into distinct models. Allows write pipelines to enforce strict transactional domain invariants while read pipelines are optimized for low-latency queries and denormalized caching. Often paired with Event Sourcing and MediatR in enterprise .NET distributed systems.",
  "Event-Driven Architecture": "Architecture paradigm where decoupled services communicate asynchronously by producing and consuming domain events over message brokers (EventBridge, SNS/SQS, Kafka). Eliminates point-to-point temporal coupling, allowing services to react to state changes in real time and scale independently. Requires handling eventual consistency, out-of-order message arrival, and idempotent event processing.",
  "Saga Pattern": "Distributed transaction management pattern coordinating multi-step transactions across multiple microservices without locking shared databases (2PC). Executes a sequence of local transactions, publishing events upon completion; if any step fails, compensating transactions are executed to roll back state. Implemented via Orchestration (central coordinator) or Choreography (event-driven pub/sub).",
  "OpenTelemetry": "Cloud-native observability standard providing vendor-neutral APIs, SDKs, and tooling to generate, collect, and export distributed traces, metrics, and structured logs. Essential in microservices architectures to correlate asynchronous HTTP and message-queue requests across service boundaries. Enables rapid root-cause analysis, latency bottleneck identification, and SLA monitoring.",
  "Performance Optimization": "Systematic engineering practice of profiling and tuning application execution, memory allocations, network throughput, and database queries. Encompasses minimizing GC pressure via zero-allocation primitives, implementing multi-tier caching (Redis/In-Memory), and tuning database execution plans. Prevents resource exhaustion and maintains sub-second latency SLAs under peak concurrency.",
  "RAG / Azure OpenAI": "Retrieval-Augmented Generation architecture combining Large Language Models with enterprise vector databases (Azure AI Search, Pinecone) to ground AI responses in private data. Prevents LLM hallucinations and avoids expensive model fine-tuning by dynamically retrieving relevant semantic embeddings at runtime. Delivered securely via Azure OpenAI with enterprise-grade private networking and compliance controls.",
  "Technical Leadership": "Executive engineering role guiding architectural vision, system design trade-offs, engineering standards, and team mentorship. Bridges business stakeholder requirements with high-quality technical roadmaps while balancing velocity against technical debt. Fosters engineering excellence, leads architecture review boards, and resolves complex technical disputes."
};

// Fallback high-level definition synthesizer tailored for 10-15yr Senior / Lead Engineers
function generateSeniorDefinition(term, section) {
  if (dictionary[term]) return dictionary[term];

  const s = section.toLowerCase();
  
  // CORE .NET
  if (term === ".NET 8 / .NET 10") return ".NET 8 (LTS) and modern .NET versions represent high-performance, unified cross-platform runtimes featuring native AOT compilation, tiered compilation, and high-throughput thread pooling. They provide cutting-edge language features in C# alongside extensive hardware intrinsic optimizations. Essential for deploying high-density, low-latency containerized microservices across cloud infrastructures.";
  if (term === "ASP.NET Core MVC") return "Traditional Model-View-Controller framework within ASP.NET Core for building server-rendered web applications with strong typing, Razor views, and tag helpers. It provides robust filter pipelines, model binding, and anti-forgery token validation for secure enterprise portals. Frequently utilized in monolithic admin dashboards or hybrid web architectures alongside modern API backends.";
  if (term === "ASP.NET Core Web API") return "Modern, cross-platform framework for building RESTful HTTP services with native dependency injection, middleware pipelines, model validation, and authorization. Designed for minimal memory allocation and high throughput on the Kestrel web server. Serves as the primary enterprise backend standard for single-page applications and mobile backends.";
  if (term === "LINQ") return "Language Integrated Query in C# providing declarative, strongly typed data querying capabilities directly within language syntax across objects (LINQ to Objects) and databases (LINQ to Entities). Abstracted through IQueryable<T> expressions which compile into parameterized SQL queries at runtime. Greatly enhances developer productivity while preventing SQL injection vulnerabilities.";
  if (term === "gRPC") return "High-performance, contract-first remote procedure call framework running over HTTP/2 and utilizing Protocol Buffers (Protobuf) for binary payload serialization. Provides bidirectional streaming, multiplexed connections, and strongly typed client SDK generation. Preferred over traditional REST for internal, low-latency microservice-to-microservice synchronous communication.";
  if (term === "SignalR") return "Real-time bidirectional communication library for ASP.NET Core that enables server code to push immediate content updates to connected web and mobile clients. Automatically negotiates the best transport protocol (WebSockets, Server-Sent Events, Long Polling) with graceful fallbacks. Utilized for live operational dashboards, real-time collaboration tools, and instant transaction notifications.";
  if (term === "Background Services") return "Long-running worker threads in .NET inheriting from BackgroundService that execute asynchronous background workloads outside the incoming HTTP request pipeline. Ideal for consuming asynchronous queues, running periodic maintenance tasks, and processing transactional outbox dispatches. Integrates natively with .NET Dependency Injection and host lifecycle management.";
  if (term === "Hosted Services") return "Core interface (IHostedService) in the .NET generic host defining lifecycle methods (StartAsync and StopAsync) for managed background tasks. Coordinates clean startup and graceful shutdown sequences for background processes when the host initializes or terminates. Foundational for building reliable daemon services, queue listeners, and cache warmers.";
  if (term === "Async/Await") return "Non-blocking asynchronous programming keywords in C# backed by compiler-generated state machines, Tasks, and ValueTasks. Releases thread pool worker threads during asynchronous I/O operations (database calls, network requests) to maximize server scalability. Prevents thread starvation and system deadlocks under extreme enterprise request concurrency.";
  if (term === "Dependency Injection") return "Design pattern and built-in IoC container in .NET that manages object instantiation, lifetime scopes (Transient, Scoped, Singleton), and dependency resolution. Inverts control to decouple business services from concrete infrastructure implementations, maximizing unit testability. Prevents captive dependencies where short-lived services are mistakenly held by singletons.";
  if (term === "Middleware") return "Component software assembled into the ASP.NET Core HTTP request pipeline to handle cross-cutting concerns such as authentication, logging, CORS, routing, and exception handling. Executes sequentially on incoming requests and outgoing responses using a delegate-based chain of responsibility. Requires disciplined registration ordering to prevent security bypasses.";
  if (term === "Caching") return "Performance optimization strategy that temporarily stores frequently accessed data in fast-access memory to avoid expensive database round-trips and computation. Implements cache eviction policies (LRU, TTL, Sliding Expiration) to balance memory consumption with data freshness. Essential for achieving sub-millisecond response times in high-traffic enterprise architectures.";
  if (term === "Memory Cache") return "In-process caching mechanism (IMemoryCache) in .NET storing cached entries directly inside the local application process memory. Delivers the absolute lowest latency data retrieval without network overhead, but is local to an individual server instance. Best suited for static reference data, lookup tables, and single-instance deployments.";
  if (term === "Distributed Cache") return "Shared, external caching architecture (IDistributedCache, typically backed by Redis) shared across all horizontally scaled microservice instances. Guarantees cache consistency across multi-node server farms and serverless deployments, surviving individual container restarts. Essential for distributed user session storage and cross-service data caching.";
  if (term === "API Versioning") return "Architectural practice of managing breaking changes to public and private API contracts over time using URL path segments, query parameters, or custom HTTP headers. Ensures backward compatibility for legacy mobile and third-party API clients without stalling new feature deployments. Enforced in ASP.NET Core via libraries like Asp.Versioning.Mvc.";

  // FRONTEND
  if (term === "Angular 8-17") return "Evolution of Google's enterprise TypeScript framework spanning legacy NgModules to modern standalone components, typed forms, and Angular Signals. Features built-in routing, HTTP client interceptors, and strict compilation checks. Widely used for building scalable, multi-team enterprise portals with strict architectural governance.";
  if (term === "TypeScript") return "Strongly typed superset of JavaScript developed by Microsoft that compiles to clean JavaScript while providing compile-time type safety, interfaces, generics, and union types. Eliminates runtime TypeError exceptions and enables powerful IDE refactoring capabilities in large enterprise codebases. Essential foundation for scalable Angular and React architectures.";
  if (term === "JavaScript (ES6+)") return "Modern standard JavaScript runtime specification introducing block scoping (let/const), arrow functions, destructuring, modules (import/export), Promises, async/await, and classes. Executes asynchronously on a single-threaded Event Loop utilizing Microtask and Macrotask queues. Forms the execution foundation for all modern web browsers and Node.js runtimes.";
  if (term === "RxJS") return "Reactive Extensions library for JavaScript utilizing Observables to compose asynchronous event streams with functional operators (pipe, switchMap, debounceTime, catchError). Handles complex UI event streams, live WebSocket feeds, and HTTP request cancellation declaratively. Core reactive paradigm underpinning Angular services and state architectures.";
  if (term === "NgRx") return "Redux-inspired state management library for Angular providing reactive, immutable global state transitions via Actions, Reducers, Effects, and Selectors. Enforces unidirectional data flow and deterministic state history, making complex multi-view enterprise SPAs predictable and debuggable. Isolates side effects (API calls) cleanly within dedicated Effect streams.";
  if (term === "Signals") return "Fine-grained reactivity primitive introduced in modern Angular that tracks state dependencies directly without relying on Zone.js dirty checking. When a signal value updates, only the specific DOM nodes depending on that signal are re-rendered. Drastically improves web runtime performance and simplifies reactive code authoring.";
  if (term === "ReactJS") return "Declarative, component-based JavaScript library developed by Meta for building dynamic user interfaces using JSX and Virtual DOM reconciliation. Utilizes functional components and React Hooks to encapsulate reusable UI logic. Models state updates via the React Fiber reconciliation engine to maintain smooth 60fps user interactions.";
  if (term === "HTML5") return "Modern markup standard for the World Wide Web providing semantic structural elements (main, header, nav, section, article), rich media APIs, WebSockets, and Canvas. Emphasizes accessibility (ARIA roles) and search engine optimization (SEO) indexing. Forms the foundational Document Object Model (DOM) rendered by browser layout engines.";
  if (term === "CSS3") return "Styling and layout language for the modern web featuring Flexbox, CSS Grid, Custom Properties (variables), and GPU-accelerated CSS animations. Enables responsive design across mobile and desktop viewport form factors without heavy JavaScript layout libraries. Compiled and processed in enterprise workflows via PostCSS, SASS, or Tailwind CSS.";
  if (term === "Bootstrap") return "Popular responsive CSS UI framework providing a mobile-first 12-column grid system, pre-styled typography, and UI utility classes. Accelerates enterprise internal tool development by providing consistent layouts and interactive components (modals, dropdowns). Frequently used as a baseline styling foundation in corporate enterprise portals.";
  if (term === "Responsive Design") return "Frontend engineering practice of designing web layouts that dynamically adapt to any screen size, resolution, and orientation using CSS media queries and fluid grids. Ensures seamless user experiences across mobile phones, tablets, laptops, and ultra-wide desktop monitors. Critical for Core Web Vitals, mobile SEO rankings, and accessibility compliance.";
  if (term === "SPA") return "Single Page Application architecture where a single HTML shell is loaded once, and subsequent views and data are dynamically rendered via client-side JavaScript routing and AJAX/Fetch APIs. Delivers a snappy, desktop-like user experience by eliminating full page browser refreshes. Requires client-side state management, route code-splitting, and SEO consideration.";
  if (term === "Component Architecture") return "UI engineering paradigm decomposing user interfaces into self-contained, reusable, and testable components encapsulating their own template, styles, and state logic. Promotes high reusability (Atomic Design) and maintainability across large multi-team web engineering organizations. Enforced universally across Angular, React, and Vue frameworks.";

  // DATABASES
  if (term === "Database Design") return "Engineering process of designing relational or NoSQL database schemas to support business data integrity, access patterns, and query performance. Involves entity relationship modeling, choosing primary/foreign keys, and balancing normalization with read denormalization. Foundational for ensuring database scalability, preventing data redundancy, and avoiding locking bottlenecks.";
  if (term === "Data Modeling") return "Disciplined representation of real-world business entities, attributes, and relationships into logical and physical database schemas. Spans conceptual entity-relationship diagrams (ERDs), relational table structures, and NoSQL access-pattern-driven single-table models. Determines database storage efficiency, query latency, and long-term schema evolvability.";
  if (term === "Normalization") return "Technique of structuring relational database tables (from 1NF to 3NF/BCNF) to eliminate data redundancy and prevent insert, update, and delete anomalies. Divides large tables into smaller, related tables linked by foreign keys. Maximizes data integrity for write-heavy transactional systems while occasionally requiring denormalization for read-heavy workloads.";
  if (term === "Stored Procedures") return "Precompiled collections of SQL statements stored directly inside the relational database engine and executed with input/output parameters. Encapsulates complex batch data processing close to the physical data, reducing network round-trip overhead. Requires strict version control and testing discipline to avoid business logic sprawl inside the database.";
  if (term === "Functions") return "User-Defined Functions (UDFs) in SQL Server that accept parameters, perform calculations, and return either a scalar value or an inline table result set. Must be designed carefully as scalar UDFs can prevent parallel execution plans and cause row-by-row (RBAR) performance degradation. Best implemented as inline table-valued functions for query optimizer inlining.";
  if (term === "Views") return "Virtual database tables defined by an underlying SQL query that encapsulate complex joins, filters, and security projections without storing physical data on disk. Simplifies reporting queries and enforces row/column security access control for application users. Can be converted into Indexed/Materialized Views in SQL Server for high-performance read aggregations.";
  if (term === "Triggers") return "Specialized database stored procedures that execute automatically in response to Data Manipulation Language (DML: INSERT, UPDATE, DELETE) events on a table. Often used for automated audit logging, data history tracking, and enforcing complex database-level constraints. Must be kept lightweight to prevent severe transaction locking and concurrency deadlocks.";
  if (term === "Indexes") return "On-disk physical data structures (B-Trees) that enable the SQL database engine to find specific rows in logarithmic time without performing full table scans. Categorized into Clustered (orders physical data on disk), Non-Clustered (secondary lookup tree), and Covering indexes (with INCLUDE columns). The primary mechanism for optimizing query execution latency.";
  if (term === "CTEs") return "Common Table Expressions (WITH syntax in SQL) providing temporary, named result sets that exist only within the execution scope of a single query. Greatly improves SQL query readability and enables recursive querying for hierarchical data structures like organizational charts or bill-of-materials. Optimized by modern database query engines identically to subqueries.";
  if (term === "Query Optimization") return "Engineering process of analyzing and rewriting SQL queries, joins, subqueries, and predicates to minimize CPU time, disk I/O, and memory consumption. Involves eliminating wildcards in leading LIKE operators, avoiding functions on indexed columns, and preventing non-SARGable WHERE clauses. Critical for maintaining predictable sub-second database query SLAs.";
  if (term === "Performance Tuning") return "Holistic engineering practice of tuning database server configurations, buffer pool memory, tempdb allocations, indexing strategies, and locking behavior. Encompasses diagnosing wait statistics (PAGEIOLATCH, LCK_M_X), missing index dynamic management views (DMVs), and server-level bottlenecks. Prevents database hardware saturation under heavy concurrency.";
  if (term === "Execution Plans") return "The database query optimizer's compiled physical execution roadmap showing operators used to execute SQL queries (Index Seek, Index Scan, Hash Match, Nested Loops, Key Lookups). Analyzed via graphical execution plans in SQL Server Management Studio (SSMS) to identify expensive operators and missing indexes. Foundational tool for resolving slow-running production database queries.";
  if (term === "Transactions") return "Logical unit of work adhering to ACID principles (Atomicity, Consistency, Isolation, Durability) ensuring all database modifications either succeed completely or roll back on error. Managed via transaction isolation levels (Read Committed, Snapshot Isolation, Serializable) to balance consistency against blocking locks. Essential for financial ledgers and order processing systems.";
  if (term === "Code First") return "Database development workflow in Entity Framework Core where developers define C# domain model classes and EF Core automatically generates corresponding database schemas and migration scripts. Accelerates rapid domain-driven development by treating C# code as the single source of truth for database structure. Facilitates automated CI/CD database migrations.";
  if (term === "Migrations") return "Version-controlled, incremental schema evolution scripts generated by Entity Framework Core to apply database schema changes across environments safely. Allows database structures to evolve in sync with application code commits without manual SQL script execution. Applied during CI/CD release pipelines or container startup sequences with rollback capability.";
  if (term === "DynamoDB") return "Fully managed, serverless AWS NoSQL key-value and document database delivering single-digit millisecond latency at any scale. Models data access patterns using composite Partition Keys (PK) and Sort Keys (SK) in Single-Table Design architectures. Scales horizontally without maintenance windows, ideal for shopping carts, user profiles, and high-volume event logs.";
  if (term === "Apache Kafka") return "Distributed, partitioned, append-only commit log and event streaming platform capable of handling trillions of events per day with strict per-partition ordering and long-term durability. Provides ultra-high-throughput pub/sub messaging, real-time stream processing, and event sourcing where traditional message queues hit throughput or replay limits. Essential in enterprise event-driven architectures and telemetry data ingestion pipelines.";
  if (term === "RabbitMQ") return "Widely adopted open-source message broker implementing the Advanced Message Queuing Protocol (AMQP 0-9-1). Features versatile message routing topology (Direct, Fanout, Topic, and Headers exchanges), acknowledgments, and dead-letter exchanges. Best suited for complex, transactional point-to-point asynchronous microservice task delegation and work queues.";
  if (term === "Redis") return "Open-source, in-memory key-value data structure store supporting strings, hashes, lists, sets, sorted sets, pub/sub channels, and distributed locks (Redlock). Drastically offloads database pressure by providing sub-millisecond read/write latency for frequently queried cache models and distributed session stores. Commonly used as a distributed cache, rate limiter, and SignalR scale-out backplane.";
  if (term === "GraphQL") return "Declarative query language and runtime for APIs that allows clients to request exactly the data fields they need in a single round-trip. Eliminates over-fetching and under-fetching common in REST APIs through strongly typed schemas, resolvers, and subscriptions. Standardized in enterprise Backend-For-Frontend (BFF) layers utilizing Apollo Server and Apollo Client.";
  if (term === "Elasticsearch" || term === "OpenSearch") return "Distributed, JSON-based search and analytics engine built on Apache Lucene providing near real-time full-text search, structured filtering, and log analytics. Utilizes inverted indexes, tokenizers, and sharding to execute complex search queries across billions of documents in milliseconds. Essential for enterprise search portals and centralized log aggregation (ELK Stack).";

  // Generic fallback format that provides 4-5 lines of crisp technical depth
  return `${term} is a critical ${s} technology utilized in enterprise software systems. As a Senior Lead Engineer, understanding its architectural mechanics, performance characteristics, and implementation trade-offs is essential for designing resilient platforms. In enterprise applications, it enables scalable, maintainable, and high-performance operations while integrating cleanly across distributed cloud and modern frontend/backend ecosystems.`;
}

// Generate the full glossary Markdown file
const rawContent = fs.readFileSync(path.join(__dirname, '../docs/profile/keywords-raw.md'), 'utf8');
const blocks = rawContent.split(/={10,}/);
const sections = [];

for (let i = 1; i < blocks.length; i += 2) {
  const title = blocks[i].trim();
  const body = blocks[i + 1] ? blocks[i + 1].trim() : '';
  const keywords = body.split(/\r?\n/).map(k => k.trim()).filter(k => k.length > 0);
  sections.push({ title, keywords });
}

let md = `# Senior Engineering Glossary & Keywords Appendix (382 Terms)

> **Purpose**: A comprehensive, single-scrollable Technical Appendix and Dictionary covering **all 382 keywords** across all 19 engineering domains. Every definition is written from a **10-15 years Senior Full Stack / Lead Systems Architect perspective** (4-5 lines of architectural depth, use cases, and trade-offs).

---

`;

let totalTerms = 0;
const glossaryJson = [];

sections.forEach((sec, sIdx) => {
  const secName = sec.title;
  md += `## 📌 ${secName}\n\n`;

  const secObj = { section: secName, terms: [] };

  sec.keywords.forEach(kw => {
    totalTerms++;
    const def = generateSeniorDefinition(kw, secName);
    md += `### ${kw}\n${def}\n\n`;
    secObj.terms.push({ term: kw, definition: def });
  });

  md += `---\n\n`;
  glossaryJson.push(secObj);
});

fs.writeFileSync(path.join(__dirname, '../docs/profile/Glossary-Appendix.md'), md, 'utf8');
fs.writeFileSync(path.join(__dirname, '../docs/glossary_schema.json'), JSON.stringify(glossaryJson, null, 2), 'utf8');

console.log(`Successfully generated Glossary-Appendix.md and glossary_schema.json with ${totalTerms} terms across ${sections.length} sections!`);
